config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/settings'
  get 'pages/terms'
  get 'pages/download'

  root 'pages#index'

  post 'pages/uploadFile' => 'pages#uploadFile'
  post 'pages/downloadFile' => 'pages#downloadFile'
  post 'pages/resetSettings' => 'pages#resetSettings'
  post 'pages/configure' => 'pages#configure'
  get 'download' => 'pages#download'
  get 'upload' => 'pages#index'
  get 'settings'=> 'pages#settings'
  get 'terms' => 'pages#terms'

end

app/models/defile.rb
class Defile < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
#init dependencies 
require 'zip'
#end dependencies

class PagesController < ApplicationController
  def index
    sweepFile
    
  end

  def sweepFile
    Defile.order(created_at: :desc).all.each do |f|
      if (DateTime.now.to_i - f.toDestroy.to_i) > 0
        puts "DELETE: " + f.name
        File.delete(Rails.root.join('public','files',f.maskedName + 'a.zip'))
        f.destroy
      elsif (not f.nil?) && f.maxlim <= f.downloads
        puts "DELETE: " + f.name
        File.delete(Rails.root.join('public','files',f.maskedName + 'a.zip'))
        f.destroy
      end
    end
  end
  
  def resetSettings
    cookies[:units] = 'min'
    cookies[:time] = '10'
    cookies[:interval] = '1'
    redirect_to "/"
  end
  
  def uploadFile
    if not verify_recaptcha
      flash[:notice] = "You need to complete the recaptcha."
      redirect_to "/"
    else
      fileObject = params[:upload][:file] #the file
      timeToDestroy = params[:upload][:time] #timer in (units)
      units = params[:upload][:units] #units of time. {'min','hours'}
      maxlim = params[:upload][:interval] #download limit
      code = params[:upload][:code] #custom code
      
      #checks the size of the file if the client side fails to.

      if fileObject.size >=52428801
        flash[:notice] = "File size is too large. Needs to be under 51MB."
        redirect_to "/"
      end
      
      #check the length of the code. handles accordingly
      if code.length <= 0
        code = randomCode()
        while not Defile.find_by_filecode(code).nil?
          code = randomCode()
        end
      end
      
      #checks the length of the download limit. handles accordingly
      if maxlim.length <=0
        if cookies[:interval]
          maxlim = cookies[:interval].to_i
        else
          maxlim = 1
        end
      end
      
      #checks the timer. handles accordingly
      if timeToDestroy.length <= 0
        if cookies[:time]
          timeToDestroy = cookies[:time].to_i
        else 
          timeToDestroy = 10
        end
      end
      
      timeToDestroy = timeToDestroy.to_i
      
      #checks the units of the cookies/website.
      if units == 'min' or (cookies[:units] == 'min')
        hours = DateTime.now + timeToDestroy.minutes
      else
        hours = DateTime.now + timeToDestroy.hours
      end
      
      
      #creates the file name.
      maskedFileName = SecureRandom.hex(3)
      while Defile.exists?(maskedFileName)
        maskedFileName = SecureRandom.hex(3)
      end
      
      #creates file object. save into databse
      Defile.create(name: fileObject.original_filename, maskedName: maskedFileName, toDestroy: hours, filecode: code,maxlim: maxlim,downloads:0)
      binaryCode = fileObject.read
      
      #saves the zip
      Zip::File.open(Rails.root.join('public','files',maskedFileName + 'a.zip'), Zip::File::CREATE) do |zipfile|
        zipfile.get_output_stream(fileObject.original_filename)  { |os| os.puts(binaryCode)}
      end
      
      flash[:success] = "Your file code is #{code} " 
      #yay, finished! redirect    
      redirect_to "/"
    end
  end
  
  def randomCode
    randomword = ""
  
    prng = Random.new
    filenum = prng.rand(1..5) #choose which word file
    prng2 = Random.new
    wordnum = prng2.rand(1..278) - 1 #choose line number from word file
       
    #get the random word
    File.open(Rails.root.join('public','words', filenum.to_s + '.txt'),'r') do |file|
      wordnum.times { file.gets }
      randomword = file.gets
    end

    return randomword.strip()
  end
  
  
  def downloadFile
    sweepFile
    fileName = params[:download][:code]
    if Defile.find_by_filecode(fileName).nil?
      flash[:notice] = "File code '#{fileName}' has not been found."
      redirect_to "/download"
    else
      Defile.update(Defile.find_by_filecode(fileName).id, downloads: Defile.find_by_filecode(fileName).downloads + 1)
      content = ""
      Zip::File.open(Rails.root.join('public','files',Defile.find_by_filecode(fileName).maskedName + 'a.zip')) do |zip|
        zip.each do |file|
          puts "OMFG I READING IT::::::"
          content = file.get_input_stream.read
        end
      end

      send_data(content, filename: Defile.find_by_filecode(fileName).name)
      
    end
  end
  
  '''
  START SETTINGS
  '''
  
  def configure
    time = params[:config][:time]
    units = params[:config][:units]
    interval = params[:config][:interval]
    cookies.permanent[:time] = time
    cookies.permanent[:units] = units
    cookies.permanent[:interval] = interval
    flash[:notice] = "Success. All configs are updated"
    redirect_to "/"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/download.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><b>Dropex</b></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Upload</a></li>
            <li class="active"><a href="/download">Download</a></li>
            <li><a href="/settings">Settings</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/terms">Terms of Use</a></li>
            <li><a href="../navbar-static-top/">About</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>




<center>
    <br><br><br><br><br><br><h1>download</h1>
    <style>
        h1 {
            font-size: 40px;
        }
        .help-block{
            font-size:10px;
            visibility: hidden;
        }
        .input-group {
            width: 10%;
        }
        #downloadfield {
            height: 20%;
            font-size: 50px;
            text-align: center;
        }
        #submit {
            width: 100%;
        }
        
    </style>
    <p id="notice">
    <% if flash[:notice] %>
        <div class="notice"><b><%= flash[:notice] %></b></div>
     <%else%>
         enter a provided file code to download a file
     <% end %>
     </p>
    
    <%=form_for :download, url: pages_downloadFile_path do |f|%>
        <div class="input-group">
       <%=f.text_field :code,id: "downloadfield",class:'form-control',placeholder: 'code',maxlength: "6"%>
        <%=f.submit "Download",id:"submit",class:"btn btn-default"%>
         </div>
       
    <%end%>
    
   
    <br><br><br><br><br>
    <a href="/">To upload a file, click here.</a>
    
    
    
    

    
</center>

app/views/pages/settings.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><b>Dropex</b></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Upload</a></li>
            <li ><a href="/download">Download</a></li>
            <li class="active"><a href="/settings">Settings</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/terms">Terms of Use</a></li>
            <li><a href="../navbar-static-top/">About</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


<style>
    h1 {
        text-align: center;
    }
    p {
        text-align: center;
    }
    h3 {
        text-align: center;
        font-weight: bold;
    }
    #form {
        width: 20%;
        text-align: center;
        float: center;
    }
    form {
        width:50%;
        font-size: 100%
        
    }
    select {
        width:100%;
        text-align: center;
    }
    
</style>
<center>
<br><br><br><br><h1><h1>local settings</h1>
<%if flash[:notice]%>
    <%=flash[:notice]%>
<%else%>
    <p id="notice">These settings will be saved as long as cookies are enabled on this computer.</p>
<%end%>
<br>
<%=form_for :config, url: pages_configure_path do |f|%>
    <h3>Timer</h3>
    <p>Set the default time 'till your file self destructs.</p>
    <div id="form">
        <%=f.text_field :time, id:"time", placeholder: "set default time", class: "form-control"%>
        <%= f.select :units, [['Minutes','min'],['Hours','hour']] ,id:"units"%><br>
        
        <br>
        <h3>Download limit</h3>
        <p>Set the default download limit.</p>
        <%=f.text_field :interval , placeholder:"download limit", id: "limit",class:"form-control"%><br><br>
        <%=f.submit "Save settings", :onclick => "return checkFields();"%>
    </div>
<%end%>
<%= form_for :reset, url: pages_resetSettings_path do |f|%>
    <%=f.submit "Reset settings to default"%>
<%end%>
<script>
    function checkFields() { 
        if((document.getElementById("config_units").value == "min" &&parseFloat((document.getElementById("time")).value) >=2881) || (document.getElementById("config_units").value == "hour" && parseFloat((document.getElementById("time")).value) >=49)) {
            document.getElementById("notice").innerHTML = "The file must be set to self destruct by no more than 2 days.";
                
        }
        else if(document.getElementById("limit").value.length >= 99 || parseInt(document.getElementById("limit").value) <= 0) {
            document.getElementById("notice").innerHTML = "The download limit must be 1 <= download limit > 99 characters long";
        } else if (isNaN(document.getElementById("time").value)) {
            document.getElementById("notice").innerHTML = "The timer time must be a valid number bigger than 0.";
        } else if (isNaN(document.getElementById("limit").value)) {
            document.getElementById("notice").innerHTML = "The download limit must be a valid number bigger than 0 or left blank.";
        } else if(document.getElementById("time").value.length <= 0 ||document.getElementById("limit").value.length <= 0 ) {
            document.getElementById("notice").innerHTML = "The fields cannot be left empty.";
        }
        else {
            return true;
        }
            return false;
        }
        
</script>
</center>

app/views/pages/terms.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><b>Dropex</b></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Upload</a></li>
            <li><a href="/download">Download</a></li>
            <li><a href="/settings">Settings</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="/terms">Terms of Use</a></li>
            <li><a href="../navbar-static-top/">About</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


  <!-- Page Content -->
    <div class="container">
        <div class="row">
        	<br><br><br>
        	<center><h1><b>Dropex</h1> <h3>Terms of Service and Privacy Policy</h3></b></h1>
        	<span id="helpBlock" class="help-block">Just in case if you try to sue me.</span>

        	</center><br>
        	<h4>INTRODUCTION</h4>
<li>Dropex.co provides a service for uploading and/or downloading files by the users. 
Dropex.co is managed by an administrator that has the right to modify the terms of service at any time without notice.</li>
<li>When uploading or downloading a file in this website, you are agreeing to the terms of service.</li>


<br><h4>TERMS OF SERVICE</h4>
<li>Dropex.co does not allow files being uploaded which violates pornographic, copyright, or illegal laws of the United States of America. Upon notice, these files will be deleted immediately. </li>
<li>Files that are uploaded onto Dropex.co will not be responsible for any damages done by the uploader’s actions.</li>
<li>Dropex.co is not responsible on who will have access to the files a user uploads. The secret code given to the user is the user’s responsibility.</li>
<li>Files uploaded onto Dropex.co are entitled to be copyright to the owner. Dropex.co is not in any way affiliated with the files being uploaded onto Dropex.co and the hosting provider.</li>
<li>All legal responsibility on the files being uploaded rests on the user uploading the file.</li>
<li>By downloading or uploading in Dropex.co, you, the user will agree not to bring Dropex.co into any type of legal action.</li>
<li>If a file uploaded in Dropex.co’s servers and raises suspicion of breaking the terms of service, Dropex.co holds the right to scan, investigate, or remove the file.</li>

<br><h4>PRIVACY POLICY</h4>
<li>Dropex.co stores cookies on the user’s computer if the user chooses to. Cookie storing happens only when one changes the settings.</li>
<li>Files being uploaded will be masked with a secret code you’re given upon uploading. These files are stored in a secure server where anyone who has access to the code will be able to download these files. These files may be removed if it raises suspicion upon legal issues.</li>
<br><h4>EXCEPTION TO THE PRIVACY POLICY</h4>
<li>Requested files and information being kept in our database will be handed over to US government authorities upon request.</li>
<li>If a user breaks the terms of service set by Dropex.co, the respective file uploaded by the user will be removed immediately.</li>
<br><br><br><br><br><%=link_to "back home", "/"%><br><br><br><br><br><br><br><br><br><br>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->